---
version: "3.9"
services:

  minecraft:
    image: itzg/minecraft-server:latest
    environment:
      EULA: "true"
    ports:
      - "25565:25565"
    volumes:
      - data:/data"
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  data: {}
