---
version: "3.3"
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_LOG_MODE=console file 
# user: '104'
    volumes:
      - grafana-storage:/var/lib/grafana
      - grafana-dashboards:/etc/grafana/provisioning
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus






volumes:
  grafana-storage:
    external: true
  grafana-dashboards:
    external: true
  prometheus-data:
    external: true
