---
version: "3.3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
# user: '104'
    volumes:
      - grafana-storage:/var/lib/grafana
      - grafana-dashboards:/etc/grafana/provisioning
volumes:
  grafana-storage:
    external: true
  grafana-dashboards:
    external: true
